server:
  port: 9004

spring:
  application:
    name: market-gateway-service
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9007/
  rabbitmq:
    host: 47.100.27.144
    port: 5672
    username: guest
    password: guest
    zipkin:
      rabbitmq:
        queue: zipkin

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5 # 每隔5秒发送一次心跳
    leaseExpirationDurationInSeconds: 10 # 10秒不发送就过期
    preferIpAddress: true
    ipAddress: 127.0.0.1
    instanceId: ${spring.application.name}:${server.port}

zuul:
  routes:
    user-service:
      path: /user/**
    user-interface:
      path: /useri/**

