server:
  port: 9006
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liu281401/market-config-service.git
        search-paths: classpath:/conig-repo/

  #          username: liu281401
#          password: qq281401
  application:
    name: config-service